"""Constants for Proxmox Custom Sensors integration."""

DOMAIN = "proxmox_sensors"

# Connection settings
CONF_HOST = "host"
CONF_USER = "user"                 # E.g.: root@pam or monitor@pbs
CONF_PASSWORD = "password"         # API Token secret or user password
CONF_TOKEN_ID = "token_id"         # Token Name (e.g., ha-token)
CONF_TOKEN_SECRET = "token_secret" # The Secret generated by Proxmox

# Server configuration
CONF_NODE = "node"                 # Target node name
CONF_PLATFORM_TYPE = "platform_type"
CONF_SENSORS = "sensors"

# Supported server types
SERVER_PVE = "PVE"
SERVER_PBS = "PBS"

# Additional configuration attributes 
CONF_VERIFY_SSL = "verify_ssl"
CONF_PORT = "port"

# Proxmox Panel URLs (Frontend enhancement)
PANEL_REPO_VERSION_URL = "https://raw.githubusercontent.com/Javisen/proxmox_panel/main/panel/version.json"
PANEL_REPO_FILES_URL = "https://raw.githubusercontent.com/Javisen/proxmox_panel/main/panel/files.json"
PANEL_REPO_BASE_URL = "https://raw.githubusercontent.com/Javisen/proxmox_panel/main/panel/"

# Local storage paths
PANEL_LOCAL_PATH = "www/proxmox_panel"
PANEL_STORAGE_FILE = ".storage/proxmox_panel_version.json"

DEFAULT_PANEL_VERSION = "0.0.0"
