name: Integration Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Integration Validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Integration validation
        uses: home-assistant/actions/ci@master
